### ISSUE TITLE
[Bug] Editing Toolbar overlaps the Tab Title Bar (View Header) and Sort Button overflows past the sidebar 

### ISSUE THREAD

**Issue by Chiehxuan-Zhang** [damiankorcz/Prism-Theme#102]
<img width="976" alt="屏幕截图 2022-12-03 075748" src="https://user-images.githubusercontent.com/93822909/205412840-12f66202-1b23-414e-8ec2-3f5436db07b7.png">
using the Editing Toolbar plugins obscures the Tab title bar.

![无标题视频——使用Clipchamp制作](https://user-images.githubusercontent.com/93822909/205413256-aad6dc5f-9423-4e1a-9d7a-b556bfa39706.gif)

**Comment by damiankorcz** [comment]
Hi @Chiehxuan-Zhang,
The issue in the first screenshot should now be resolved in version 3.1.0.

I can't seem to replicate the issue with the Sort button in the Community Themes. What system are you using? Desktop or Mobile?

P.S. Please use the template provided because it's hard for me to track issues otherwise. Next time I will just close the issue. Thanks.

**Comment by Chiehxuan-Zhang** [comment]
The problem in the first screenshot has been fixed.
