### ISSUE TITLE
Local graph becomes black after changing mode (dark/light)

### ISSUE THREAD

**Issue by kudrmax** [damiankorcz/Prism-Theme#133]
**Describe the bug**

After changing theme mode from dark to light or from light to dark colors of any part of local graph becomes black. If go to Style Setting tab -> Prism Theme -> Appearance -> Graph Color Customisation -> Graph lines color and press Restore default button, then bug disappears.

**To Reproduce**
1. Open local graph
2. Change theme mode (light/dark)

**Screenshots**

Before:
<img width="1440" alt="image" src="https://github.com/damiankorcz/Prism-Theme/assets/48362210/581229fa-26cc-480e-9b5d-760919f8f9db">

After:
<img width="1440" alt="image" src="https://github.com/damiankorcz/Prism-Theme/assets/48362210/826d67b4-c428-4129-8fd7-43ac29810482">
<img width="1440" alt="image" src="https://github.com/damiankorcz/Prism-Theme/assets/48362210/115b5222-27e2-4922-8df2-edc93ca761b9">

**Setup Information**
 - Device Type: Mac
 - Operating System: MacOS Monterey
 - Prism version: 3.3.0
 - Color Schemes Used: Swan
 - Obsidian Version: 1.3.5
 - Obsidian Installer Version: 1.3.5

**Additional context**

I tested this bug in empty new vault without any other plugin accept Style Setting, and bug still exists.

**Comment by garbosz** [comment]
+1 on this

**Setup Information**

- Device Type: laptop
- Operating System: Windows 11
- Prism version: 3.5.0
- Color Schemes Used: pistachio/pine
- Obsidian Version: 1.5.12
- Obsidian Installer Version: 1.4.13

**Comment by kazerniel** [comment]
Mine has the right colours at launch, then after a few seconds it switches to all black regardless of dark/light mode. (I usually have mode set to 'adapt to system', but it behaves the same at any mode setting.)

**Comment by FeralFlora** [comment]
I keep wondering about the colors of the local graph (or lack thereof), and then I remember this issue. Would love to see this fixed, as it's one of the few drawbacks of the Prism theme.

**Comment by damiankorcz** [comment]
I think I've finally identified the issue. Still have a few things to resolve but there will at least be a partial fix for this that prevents the colours from disappearing in the next update 🥳

**Comment by damiankorcz** [comment]
Hi all,
The partial fix should now be available in Prism 3.5.3. The update requires Obsidian app version 1.6.0 or above.

The current problem is that if you switch between Light / Dark theme the graph colours will use the shades from Swan / Raven colour schemes since the partial fix was to make those the default colours which other colour schemes replace. Strangely if you change any setting in Style Settings it triggers a reload of some kind that will load the correct colour scheme colours. Not sure how I will resolve this yet so for now it's something we'll have to deal with. I can only assume these issues are due either how Obsidian loads graph colours, how Style Settings injects the CSS or a combination of both.

Since the issue outlined has been addressed I'll close this issue but will continue to look for a solution to the above.
