### ISSUE TITLE
Standard Callouts Colours

### ISSUE THREAD

**Issue by Roniou2** [damiankorcz/Prism-Theme#162]
It is not a big issues but it is to do with the Callouts and matching other themes.
The callout are group into a number of types and so that Note, Info and ToDo all use the same colour blue. In the Prism theme you have the Note callout as grey. This means that if you switch between themes then the is no consistency.

It would be good if you could switch the colour on your Note Callout to match the colour in other themes and to treat the group of three Callouts with the same colour. 

I have been able to amend the Prism css file and get the callout to look like this.

![image](https://github.com/damiankorcz/Prism-Theme/assets/164142501/828b77eb-93c5-4ffd-96ae-983cb13c48c5)

**Comment by damiankorcz** [comment]
Hi @Roniou2,
I don't think I'll be changing the colours at this point just because they have been like this from the start and as you figured out you can change them to your liking with a fairly simple snippet.

Also, coming in the next Prism update, I'll be releasing the Prism Callouts as a CSS snippet so you can use the same style callouts and customisations in other themes so that could solve be a potential solution.

**Comment by Roniou2** [comment]
Thanks for the update and for providing such a brilliant theme package.
