### ISSUE TITLE
Colored Folders Not Working Since Update to version 3.5.2

### ISSUE THREAD

**Issue by AniccaAnitya** [damiankorcz/Prism-Theme#167]
Hello,

I am here to report a possible bug that has been going on since updating to Prism 3.5.2. Specifically, the colored folders function no longer works whether using the light or dark theme - the folders are in the default color even with the colored folders function switched on. I have tried uninstalling and reinstalling Prism 3.5.2 and resetting all customization settings in the Prism plugin to no avail. 

I would be most grateful if someone could look into the issue and fix the plugin if need be.

Just so you know, I am using Prism 3.5.2 with Obsidian v 1.5.12 on Mac OS Sonoma 17.5.

Thanks and have a good day!

**Comment by damiankorcz** [comment]
Hi @AniccaAnitya,
I just realised I messed up when setting the minimum version with Prism 3.5.1 which should have been for Obsidian 1.6.0 and onwards. I've tried to redo that specific commit / release but from what I can tell Obsidian has the previous changes cached and doesn't want to download the older (now revised) version even if I manually delete Prism from my test vault.

So for the time being you can download the following ZIP file and extract the CSS file within into `*your vault*/.obsidian/themes`. Then in Obsidian you should see `Prism 3.5.0 (Legacy)`. Use this version until Obsidian 1.6.0 or above release to the public versions at which point you can go back to the usual theme. Just remember to update it incase there are newer versions before you go back.

[Prism 3.5.0.zip](https://github.com/damiankorcz/Prism-Theme/files/15365614/Prism.3.5.0.zip)

Obsidian 1.6.0+ have changed a few things and I've already fixed Coloured Folders for those changes. Since I messed up at capping the changes to the correct Obsidian version you got the changes when you shouldn't have.

If you encounter any issues with this let me know.

Sorry for the inconvenience!

**Comment by AniccaAnitya** [comment]
> Hi @AniccaAnitya, I just realised I messed up when setting the minimum version with Prism 3.5.1 which should have been for Obsidian 1.6.0 and onwards. I've tried to redo that specific commit / release but from what I can tell Obsidian has the previous changes cached and doesn't want to download the older (now revised) version even if I manually delete Prism from my test vault.
> 
> So for the time being you can download the following ZIP file and extract the CSS file within into: `*your vault*/.obsidian/themes`
> 
> Then in Obsidian you should see `Prism 3.5.0 (Legacy)`. Use this version until Obsidian 1.6.0 or above release to the public versions at which point you can go back to the usual theme. Just remember to update it incase there are newer versions before you go back.
> 
> [Prism 3.5.0.zip](https://github.com/damiankorcz/Prism-Theme/files/15365614/Prism.3.5.0.zip)
> 
> Obsidian 1.6.0+ have changed a few things and I've already fixed Coloured Folders for those changes. Since I messed up at capping the changes to the correct Obsidian version you got the changes when you shouldn't have.
> 
> If you encounter any issues with this let me know.
> 
> Sorry for the inconvenience!


Hello Damian,

Thank you very much for your prompt and thorough reply!

I followed your instructions and have successfully installed Prism 3.5.0 (Legacy) in lieu of v3.5.2, which works fine as a temporary solution for the time being.

Thanks a bunch and take care!
