### ISSUE TITLE
Custom Callout Issue

### ISSUE THREAD

**Issue by Fabric-Florist** [damiankorcz/Prism-Theme#176]
**Describe the bug**
The icon for my custom callout is not showing up. 

**To Reproduce**
1: Create a custom callout with this code:

>.prism-theme:not(.pt-disable-callout-styling) .callout[data-callout="middleground"] > .callout-title {
    color: var(--color-yellow-text);
    background-color: var(--color-yellow-base);
    border-color: var(--color-yellow-tint);
}
>
>.prism-theme:not(.pt-disable-callout-styling) .callout[data-callout="middleground"] > .callout-title .callout-icon .svg-icon {
    color: var(--color-yellow-text);
}
>
>.prism-theme:not(.pt-disable-callout-styling) .callout[data-callout="middleground"] > .callout-content {
    background-color: hsla(var(--color-yellow-base-hsl), var(--callout-background-alpha));
    border-color: var(--color-yellow-tint);
}
>
>.callout[data-callout="middleground"] {
    --callout-icon: Handshake;
}

2: Make a middleground callout in a file
3: See no icon when callout is not selected

**Expected behavior**
I expect the icon to show up

**Setup Information**
 - Device Type: PC
 - Operating System: Windows 11
 - Prism version: 3.5.3
 - Color Schemes Used: Raven
 - Obsidian Version: 1.6.7
 - Obsidian Installer Version: 1.4.13

**Additional context**
I'm not sure if I did something wrong or if this is an actual bug. Sorry if I put this in the wrong place.

**Comment by damiankorcz** [comment]
Hi @Fabric-Florist,
It appears that Obsidian manually handles updates for Lucide, which is the icon pack they use. If this page is to be trusted as up to date it appears that Lucide version currently used is 0.268.0 which was released on Aug 14, 2023.
https://help.obsidian.md/Obsidian/Credits#Lucide

Looking at the `handshake` icon it states that it was released in 0.321.0.
https://lucide.dev/icons/handshake

So your best bet would be to make a request for the Obsidian team to update Lucide. This is best done on their forum. I've found this request a while ago: https://forum.obsidian.md/t/upgrade-lucide-icons-and-improve-timeliness-of-future-upgrades/73152

Nothing I can do about this since it's not a theme issue. For the moment you can check if an icon you want to use shows 0.268.0  or earlier version to make sure it's supported. Note you might have to fully close down a note or restart obsidian for the icon to start showing sometimes.

**Comment by damiankorcz** [comment]
Hi @Fabric-Florist,
Obsidian has updated Lucide icons to 0.446.0 in the Insider version of Obsidian (1.7.4) so you should be able to use your icon natively now.

Obsidian changelog mentioning this: https://obsidian.md/changelog/2024-10-08-desktop-v1.7.4/
