### ISSUE TITLE
support "alternate checkboxes"

### ISSUE THREAD

**Issue by eleanorkonik** [damiankorcz/Prism-Theme#20]
It would be helpful if you supported some of the data-task checkboxes that are becoming more common in the community, i.e. this snippet. 

https://publish.obsidian.md/hub/02+-+Community+Expansions/02.05+All+Community+Expansions/CSS+Snippets/Alternate+Checkboxes+(SlRvb)

Right now they're rendering like this:

![image](https://user-images.githubusercontent.com/75856959/147860757-8ff62fc8-5662-447e-82fb-fdd0e26ac664.png)

Which makes it hard for me to use your (very beautiful and clear!) theme

**Comment by damiankorcz** [comment]
Hi @eleanorkonik, I'm finally coming around to this issue. I've had a look at SlRvb's Checkboxes snippet and it appears to work fine with the theme as you can see below. Unless you meant for Prism to support it in a more native way (integrated into the theme) with a more matching style to my theme? I'd be happy to take a crack at it if that's the case. There are definitely some colours that would need adjusting for best readability.
|Light Theme|Dark Theme|
|-|-|
|![image](https://user-images.githubusercontent.com/7290097/151020765-67672104-408b-48fd-bd35-19aa045daaed.png)|![image](https://user-images.githubusercontent.com/7290097/151020861-cc251189-eba5-424c-819f-f7246cdf5bcd.png)|

**Comment by eleanorkonik** [comment]
I was mostly concerned with it not showing up in Live Preview's "editing" mode, not so much the color optimizations and stuff.

**Comment by AiurArtanis** [comment]
it will be nice if Prism-theme supports this snippet natively  @damiankorcz

**Comment by damiankorcz** [comment]
Hi @eleanorkonik and @AiurArtanis,
After a lot of deliberation about this feature, I've chosen not to implement it natively in Prism. Main point of contention for me has been the fact that despite Alternative Checkboxes appearing across multiple popular themes, there is no standardisation between the syntax used and all of them do their own take on it. This would make supporting the feature difficult since I would likely have to support all the different variants for people coming from those themes. I also don't want to do my own take on it since that would only add to fragmenting things for users.

The latest Prism release (3.0.0) should work and look fine with the latest ITS Checkboxes snippet:
https://github.com/SlRvb/Obsidian--ITS-Theme/blob/main/Snippets/S%20-%20Checkboxes.css

If there are other iterations on this feature in a CSS Snippet form and they don't work right in Prism, please let me know and I'll see what I can do to make sure it does.

Apologise for keeping this issue open so long. It's been on my mind this whole time and I didn't know how to go about it 😅

**Comment by damiankorcz** [comment]
Hi @eleanorkonik and @AiurArtanis,
I figured you might be interested in my efforts to try and standardise this feature as part of Obsidian October. I've made a thread on the Official Obsidian Discord for this and will continue all conversations about this there. Feel free to chime in: https://discord.com/channels/686053708261228577/1291469509336502272
