### ISSUE TITLE
'Style Settings' Plugin warning is shown even when Style Settings is installed and enabled

### ISSUE THREAD

**Issue by claremacrae** [damiankorcz/Prism-Theme#25]
I am creating a minimal repro for a different issue, and so have a vault with:

- Only community plugin is Style Settings
- Only core plugin is File Explorer
- No snippets

When I go to the Appearance pane, I see this:

![image](https://user-images.githubusercontent.com/4840096/148286739-e6afdd10-5d54-42ab-9d3b-46a4ea94f7db.png)

Yet community plugins settings shows this:

![image](https://user-images.githubusercontent.com/4840096/148286862-e63b67d8-40e8-4882-983b-d6a987edba16.png)

I installed Style Settings after Prism, having seen this warning.
I have reopened this vault, and yet the Style Settings warning still shows.

**Comment by claremacrae** [comment]
I tried going to the Style Settings plugin's Settings pane, and selecting "Reset all settings to default" - which created the settings file for the plugin, with this content:

```
{}
```

The warning did not go away.

**Comment by claremacrae** [comment]
I then increased the Scrollbar Width a bit, which changed the Style Settings's settings to:

```
{
  "obsidian-prism-theme@@scroll-bar-size": 12
}
```

And still I see:

![image](https://user-images.githubusercontent.com/4840096/148287795-286e635e-413a-4287-95b2-9f969d87ba34.png)

**Comment by claremacrae** [comment]
Maybe it's intended that this red warning always be shown?

**Comment by damiankorcz** [comment]
Hi @claremacrae,
I recently added the warning instead of the screenshot as that felt like the most unobtrusive and immediate way to make sure new users of the theme will know that Style Settings is a requirement. I didn't think of having it disable after Style Settings gets enabled, however it was actually quite trivial.

Style Settings adds this class `.css-settings-manager` to the Body. So I used this ` body:not(.css-settings-manager)` prefix for the selectors used to replace the screenshot with the warning and it now it will returns to normal when Style Settings is enabled and show when it's disabled.

Thank you for reporting this and taking the time to do your own testing. Will add this fix in the coming update.

**Comment by claremacrae** [comment]
Hi @damiankorcz 

Many thanks for the swift and helpful reply.

I do think the message is a good thing. From my notes, I ran Prism previously and gave up on it, and I do now wonder whether that was because I didn't have Style Settings installed...

**Comment by claremacrae** [comment]
What is the nature of the problem if Style Settings is not installed, may I ask?

**Comment by damiankorcz** [comment]
@claremacrae, It's mostly due to how I've setup the theme to work with Style Settings. The default options for customisable settings are using custom classes that are added by Style Settings to the HTML Body; hence why when it's enabled they all trigger and make the theme look as it should. If Style Settings isn't enabled they don't get picked up at all making things look unfinished/broken. Can see how that would scare away new users.

Style Settings is where the customisability, additional features and most of this theme's efforts were placed. Since a lot of popular themes also make use of it I just hopped most users would have it installed and enabled anyway making it a non issue.

Now that It has been brought up a few times by users, it's definitely on the list to fix. Just need to get around to address it 😅

**Comment by damiankorcz** [comment]
@claremacrae, Yeah it's a brilliant addition for theme makers for sure. @mgmeyers did a brilliant job with it.

For example when using custom colours I can create an option for the user to select a colour from a colour picker in Style Settings which will create a variable I specify in the `id` field; in this case `h1-border-color-custom-lt`.
![image](https://user-images.githubusercontent.com/7290097/148298836-e5d51d87-dee6-49ba-a414-ffab14634022.png)

Then I can use that variable to change the border colour like so (there are multiple formats in which the colour can be exported from the setting):
![image](https://user-images.githubusercontent.com/7290097/148298886-fc5640b2-e508-4bff-99ae-fded31d1c85b.png)

You can also triggered any CSS you want by using a custom class and prefixing it onto your selectors. The `value` fields are what will be added as custom classes to the HTML Body depending on what the user selects; in this case from a dropdown. 
In this case `pt-status-bar-position-top` will trigger all the selectors I added it to and move the Status Bar to the top of the window overlapping the Titlebar.
![image](https://user-images.githubusercontent.com/7290097/148299074-7d708547-91b3-48f8-b787-8f47dafa0dca.png)

Here for example I'm using that class stacked with another custom class to have the Titlebar Text hide when the Status Bar is set to display at the top and is aligned horizontally to the centre. Just to clarify, there are other things that these custom classes are added to make this work this is just one of them I'm using as an example.
![image](https://user-images.githubusercontent.com/7290097/148299132-8dff80fa-b2bf-4293-b838-6b23c283bf0b.png)

I hope that somewhat clarifies how, at least I, use Style Settings in Prism.

**Comment by damiankorcz** [comment]
This should now be addressed in Version 1.3.0.
