### ISSUE TITLE
A customizable bottom backlinks panel

### ISSUE THREAD

**Issue by AiurArtanis** [damiankorcz/Prism-Theme#31]
@damiankorcz 

## Advice
---
the bottom backlinks panel with Prism-Theme is cumbersome, and I want to customise it like:
![image](https://user-images.githubusercontent.com/98091664/151643309-d5771b81-5a5c-4f5d-ac07-8216de129a4a.png)
**(set the title and toolbar in the same line)**
or
![image](https://user-images.githubusercontent.com/98091664/151643463-ca3b2a3b-ffc3-49b0-ab5a-106447681930.png)
**(hide the title bar and set the toolbar in the bottom)**

## Environment
---
os: win 10
ob ver: 0.13.19
prism ver: v1.4.0

## Last
---
*hope for your reply asap*😊

**Comment by damiankorcz** [comment]
Hi @AiurArtanis,

Thanks for the feedback!

I'll probably remove the title since that's something I added for clarity but since the user has to make a conscious decision to enable the Backlinks in Document option, the title serves very little purpose. 

As for the buttons container, I don't see how having it at the bottom would be a good idea. It might look a little neater if the Linked mentions and Unlinked mentions sections are collapsed but if they aren't and have content in them you would have to scroll all the way to the bottom to adjust things.

So as a compromise here is a prototype; removed the title and made the buttons stick to the top of the page as you scroll down. I think this looks pretty good. What do you think?

![Obsidian_2022-01-29_02-54-08](https://user-images.githubusercontent.com/7290097/151644616-8f5cf753-6482-4179-af7c-cf846a5a39d1.gif)

There are a few other issues I've noticed with text alignment in there so I'll work on sorting those out as well and have this ready for the next update.

**Comment by AiurArtanis** [comment]
wow, this sticked feature is cool and it looks suitable for the theme. well, to be honest, your prototype exceeds my expectation and now I start to look forward the next update.

**Comment by damiankorcz** [comment]
This should now be addressed in Version 1.5.0.
