### ISSUE TITLE
Dark accent color with light coloured text

### ISSUE THREAD

**Issue by Chriswaterguy** [damiankorcz/Prism-Theme#41]
Is there any way I can have a dark accent color with light coloured text? Currently if I choose black, the filename text is invisible. 

For now I just disable the Style Settings plugin, and it does what I want (but I lose the ability to customise). 

Thanks :)

**Comment by damiankorcz** [comment]
Hi @Chriswaterguy, 
With the release of v2.0.0, you can now change the colour of the text that appears over accented UI elements (Go to Style Settings -> Prism Theme -> Appearance -> Accent, Color Schemes and Style -> Light/Dark Theme -> Accent Text Color Preset).  The Custom Accent Colours have also been tweaked so that you have more control over the 3 shades. Change the Accent Color Preset to Custom and you will find the new adjustment options slightly lower in Custom Accent Color Tuning.

Make sure to reset your Style Settings and restart Obsidian for the theme to work correctly after updating.

Here are the release notes for the v2.0.0 update: https://github.com/damiankorcz/Prism-Theme/releases/tag/2.0.0
