### ISSUE TITLE
Header rendering bug in exported PDF

### ISSUE THREAD

**Issue by AiurArtanis** [damiankorcz/Prism-Theme#46]
@damiankorcz hello again

## BUG
i customize the header color, and it doesn't work in exported PDF as listed below:
![image](https://user-images.githubusercontent.com/98091664/162353028-a3634428-d112-4e09-b0b9-18a151ade553.png)
_note in editor_

![image](https://user-images.githubusercontent.com/98091664/162353549-57241119-6443-4414-abdd-701a7dec64ea.png)
_exported note (preview by QuickLook)_

## Environment
Prism: V1.5.2
OB: V0.14.2
OS: Win 10

## Last
waiting for Prism V1.6 😁

**Comment by damiankorcz** [comment]
Hi @AiurArtanis,
With the release of v2.0.0, I've completely removed visual settings for headers due to a poor design on my part making them very hard to maintain going forward. I do plan on reintroducing some options, albeit more refined and easier to use than last time, in future updates. Since this option doesn't exist in the current release of Prism, this issue doesn't apply so I will close it. I'll keep this in mind when I reintroduce colour options for headers.

**Comment by AiurArtanis** [comment]
> With the release of v2.0.0, I've completely removed visual settings for headers due to a poor design on my part making them very hard to maintain going forward. I do plan on reintroducing some options, albeit more refined and easier to use than last time, in future updates. Since this option doesn't exist in the current release of Prism, this issue doesn't apply so I will close it. I'll keep this in mind when I reintroduce colour options for headers.

ok, and i will use a css snipet to customize the color of header
