### ISSUE TITLE
Highlighted text are separated into blocks in live preview when the text contains a link

### ISSUE THREAD

**Issue by yigitozgumus** [damiankorcz/Prism-Theme#57]
In live-preview mode
 
![image](https://user-images.githubusercontent.com/5840669/167314584-225a6e1c-6869-4962-8e8a-8a002b116fa5.png)

In preview mode

![image](https://user-images.githubusercontent.com/5840669/167314600-29c426c1-6823-4133-a7d4-2a7faa7d45bd.png)

**Comment by damiankorcz** [comment]
Hi @yigitozgumus,
Just an update on this issue, I've been trying to tackle it with just CSS but with the way things are structured in Obsidian across different editor views, whether the line is selected/active, etc. there is now clean way to tackle this. It has brought to my attention that similar issues also occur with Inline Code and with Quotes. I've had a semi working solution with just CSS but it's quite fragile and doesn't fully solve the issue so I've withheld from including it in the newest update (v2.2.0).

I'll try and make a Feature Request on the Obsidian forum for a potential solution; see if I can get it resolved that way. This seemingly small issue has been quite the rabbit hole 😅. I'll keep you updated on the progress once I make a Forum thread on this.

**Comment by damiankorcz** [comment]
Hi @yigitozgumus,
I've been trying to tackle this issue for a long time and have decided to drop the styling used on `==` highlights because there isn't an easy fix for it (so I've been told by the devs). The highlights now look how they would in the Default theme (simple background colour) and inherit the Accent colour you chose for the UI.
I might add a Style Settings option to change it to a preset colour or even a custom one in the future.

Sorry for taking so long to get back to you on this on!
