### ISSUE TITLE
Codeblock highlights not showing Raven + vim mode

### ISSUE THREAD

**Issue by Craftidore** [damiankorcz/Prism-Theme#59]
When in **vim mode**, using `v` or `V` to select things inside a generic codeblock, the highlight color is the same as the background and nothing is highlighted. 

<img width="246" alt="image" src="https://user-images.githubusercontent.com/73705352/167432831-06f813b2-7b4c-4278-8fce-8131fdb4768a.png">

Prism Theme Version: 2.1.0
Color Scheme: Raven
Obsidian Light/Dark Mode: Dark
Style Settings: `{}` (all defaults)
CSS Snippets: None
Community Plugins: Style Settings

**Comment by Craftidore** [comment]
Guide to troubleshooting without learning vim:

Type out 
````
```Test
Some text to select
```
````
in a file

Go to Settings → Editor, then scroll to the bottom and click the toggle to enable vim mode.

You will be taken to a screen where you are asked how to exit vim. Type out `:q!` then hit enter.

Go back to your file where you typed out the test codeblock, click the `S` with you mouse. 
Press `v`
Press `l` repeatedly until your cursor moves to the end of the line. The text is now selected. 

Press `<esc>` to exit the selection.

Before trying to do anything else, go to Settings → Editor and disable vim mode again, because Obsidian is completely unusable with vim mode unless you already know vim.

**Comment by damiankorcz** [comment]
Hi @Craftidore,
I've just tested this with Prism, Shimmering Focus and even the default theme and it seems that this is an issue on Obsidian's side. The selection is being created in the DOM and I can see it when I select it via Dev Tools but it just doesn't show up over the codeblock.

Here is a GIF showing that it's there just for some reason not rendering the background colour:
![Obsidian_2022-05-10_17-49-54](https://user-images.githubusercontent.com/7290097/167681386-4ad3a6fb-65a5-48c6-8e4f-c28a16cca36c.gif)

I'll see if there is anyway for me to fix it in the theme but this might be an issue to submit on the forum since it's also present in default theme (I've turned on Safe Mode to be sure it's not a plugin related issue).

![Obsidian_2022-05-10_17-53-12](https://user-images.githubusercontent.com/7290097/167681883-91934e9e-4c8b-4766-aa90-2568e29e1a30.gif)

Some info on my setup
OS: Windows 11
Obsidian Version: 0.14.9
Obsidian Installer Version: 0.14.6

**Comment by damiankorcz** [comment]
@Craftidore,
Looks like this specific issue has been addressed in the latest insider build v0.14.10. I'll put out some visual changes for Vim mode in the next update.
![image](https://user-images.githubusercontent.com/7290097/167702498-72dda970-ec6a-420a-aee1-9ed29f2e1d6a.png)
