### ISSUE TITLE
[FR] Change Editor Background Color

### ISSUE THREAD

**Issue by Felipe-Juan** [damiankorcz/Prism-Theme#68]
**Is your feature request related to a problem? Please describe.**
I don't believe it is. I just wanted to leave it to my personal taste, but I know there would be others who would also appreciate having this option

**Describe the solution you'd like**
Also have customization options for Editor Background, at least Custom Color

**Describe alternatives you've considered**
I imagine it's possible to change it through the CSS code, but I'm a lay person and I don't know how to do it. But in the same way, I think it's good to have this feature and have the same customization convenience as other things

**Additional context**
Example of what I would like to do (after I would match the colors with the editor's new color) -
![fdsfdsfsdf](https://user-images.githubusercontent.com/85803620/168695214-747ad440-0f5c-4690-840f-5e5d93cad47e.png)

**Comment by Felipe-Juan** [comment]
By the way, would it also be possible to change the colors of these elements? And I apologize for already being a bit nitpick �
![uiyiuyiuyuiy](https://user-images.githubusercontent.com/85803620/168695721-23fb9ecc-0ab7-478b-b863-99a841999f11.png)
�

**Comment by Felipe-Juan** [comment]
By the way, would it also be possible to change the colors of these elements? And I apologize for already being a bit nitpick 😅
![uiyiuyiuyuiy](https://user-images.githubusercontent.com/85803620/168695863-300267a9-049a-4b93-9f16-12669c6e4198.png)

**Comment by damiankorcz** [comment]
Hi @notDavid,
Why do you want to change those? Is there anything wrong with how it looks right now? Do none of the Colour Schemes strike your liking?

Also since you jumped from a pretty old version, when I made the shift to v2.0.0+ you need to reset your Style Settings to make sure everything works correctly going forward since a lot of selectors have changed in the theme.

**Comment by damiankorcz** [comment]
@Felipe-Juan  @notDavid
I don't currently plan on exploring adding additional customisation options over the existing Colour Schemes and options available in Style Settings. Right now that would require some rework due to how Prism's Colour Schemes are set up and how colour variables are used across different elements of the UI.

For now you can make your own snippets and modify the values used in a Colour Scheme to colours you prefer.For example, the variables used for the Raven Colour Scheme are located here:
https://github.com/damiankorcz/Prism-Theme/blob/4285adfdd618dfc73efb5d7370e35238f6b33f6e/src/scss/Color%20Schemes/colorSchemeBird.scss

You can take the selectors used for Colour Schemes and use them in a snippet in order to overwrite the colour variables e.g.
```css
.theme-dark.pt-color-scheme-raven-dt {
	--background-primary: red;
	--background-primary-alt: green;
	--background-secondary: blue;
	--background-secondary-blur: orange;
	--background-secondary-alt: pink;
	--background-tertiary: grey;
}
```

As for the app background colour you can customise it in the Style Settings -> Prism Theme -> Appearance -> Background Options -> Light/Dark Theme.

I'll keep this issue open for now in case there is some development for this in the future.

**Comment by JaneValleyhasBtaken** [comment]
Yes, that would be a great feature. 
I am using dark mode, but my eyes just so picky and can't get comfortable with the background colour of the editor (tried all four colour schemes).

**Comment by JaneValleyhasBtaken** [comment]
HI, just notice this issue is marked as completed and thanks for the work. However, when I dig into the Style Setting, I didn't find any option for customising background colour. Is this must be done via css?

**Comment by damiankorcz** [comment]
Hi @JaneValleyhasBtaken,
I've decided to close this issue since I don't see myself implementing the suggested features in the future.

The design has been streamlined with Prism 3.0.0 meaning that you could change the following in a snippet:

**Light Theme Colour Schemes Example**
```css
.theme-light.pt-color-scheme-swan-lt {
--background-primary: hsl(0, 0%, 0%); // black 
}
```

**Dark Theme Colour Schemes Example**
```css
.theme-light.pt-color-scheme-swan-lt {
--background-secondary-alt: hsl(0, 0%, 0%); // black 
}
```
Those variables are used for the background of the editor and other text heavy areas.

**However...**

Since all colours in each colour scheme are designed to work well together, if you start changing them e.g. changing the editor background to be white instead of dark in the Dark colour schemes, things like text, code blocks, colours, etc. will not look right since they are tuned to look correctly over a Dark background. It basically creates a cascade of issues.

It's simply not a feasible option for me to implement at the moment since it would add a lot of complexity on my end and be another thing to maintain for one or a few users. I feel that the 8 colour schemes provided are enough at the moment.
